import type {Metadata} from "next";
import "./globals.css";
import {TanstackQueryProvider} from "@/providers/tanstack-query-provider";
import React from "react";
import {Toaster} from "sonner";


export const metadata: Metadata = {
    title: "eGARC System",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
    return (
        <html lang="en" className="w-svw h-svh">
          <body className="w-svw h-svh">
            <TanstackQueryProvider>{children}</TanstackQueryProvider>
            <Toaster position={"top-left"}/>
          </body>
        </html>
    );
}
